name: Package and deploy Lambda + API-PROD

on:
    push:
        branches: ['main']

jobs:
    package_lambda_to_s3:
        name: Package and upload script to S3
        runs-on: ubuntu-latest
        steps:
            - name: AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
                aws-region: ${{ secrets.AWS_REGION }}

            - uses: actions/checkout@v5
            - name: Package and upload lambda code to S3
              env:
                S3_BUCKET: ${{ secrets.S3_BUCKET_PROD }}
                S3_PATH:   ${{ secrets.S3_PATH_PROD }}
              run: |
                zip function.zip synthesize.py
                aws s3 cp function.zip s3://$S3_BUCKET/$S3_PATH/function.zip

            - uses: actions/checkout@v5
            - name: Upload sample text to S3
              env:
                S3_BUCKET: ${{ secrets.S3_BUCKET_PROD }}
                S3_PATH:   ${{ secrets.S3_PATH_PROD }}
              run: |
                aws s3 cp speech.txt s3://$S3_BUCKET/$S3_PATH/speech.txt

    deploy_to_prod_job:
      name: Deploy lambda to prod environment
      runs-on: ubuntu-latest
      needs: package_lambda_to_s3
      steps:

        # Configure AWS credentials

        - name: AWS Credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id:      ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key:  ${{ secrets.AWS_SECRET_ACCESS_KEY}}
            aws-region:             ${{ secrets.AWS_REGION }}
        
        # Deploy to beta 
        - uses: aws-actions/setup-sam@v2
          with:
            use-installer: true
        - uses: actions/checkout@v5
        - name: Deploy lambda to prod environment
          env:
            S3_BUCKET: ${{ secrets.S3_BUCKET_PROD }}
            S3_PATH:   ${{ secrets.S3_PATH_PROD }}
          run: |
            sam deploy \
              --stack-name ${{ secrets.CF_STACK_NAME_PROD }} \
              --template-file infrastructure/cloudformation/template-prod.yml \
              --capabilities CAPABILITY_NAMED_IAM \
              --parameter-overrides \
                LambdaFunctionName=${{ secrets.LAMBDA_NAME_PROD }} \
                LambdaCodeBucket=${{ secrets.S3_BUCKET_PROD }} \
                LambdaCodeKey=${{ secrets.S3_PATH_PROD }}/function.zip \
                ApiStageName=prod \
                S3Bucket=${{ secrets.S3_BUCKET_PROD }} \
                S3BucketPrefix=${{ secrets.S3_PATH_PROD }}